{
  "data": [
    {
      "message": "מסבלט את החדר!...\nבאיזור הכי יפה ברוטשילד (פינת מאז\"ה), בבנין הכי שקט בעיר, מרחק הליכה מהכל.. \nעומד חדר גדול, מואר, ומרוהט שרק מחכה לדייר לתקופה של חודשיים, עם סיכוי להארכה (תלוי בקבלן- הבנין לפני שיפוץ מסיבי)\nמיטה זוגית, ארון קיר ענק, טלויזיה, חיבור לyes, מזגן, אינטרנט אלחוטי, שני כיווני אויר, סלון גדול ומטבח מאובזר. 2900 כולל הכל.\nלאוהבי חיות בלבד, בדירה גרים כלב וחתולה..\n\n052-5360279",
      "updated_time": "2014-02-24T15:48:35+0000",
      "id": "707688259256219_729916720366706"
    },
    {
      "message": "סבלט לחודשיים (מתחילת מרץ) בדירה ענקית ומדהימה בדובנוב פינת צייטלין, חדר גדול עם מרפסת עם שמש, סלון גדול, מטבח גדול מוארת ומאווררת. קומה 4 + מעלית. והכי חשוב עם השותפה האהובה העליי Alma Harish\n2800 שקלים חדשים\n0545869466",
      "updated_time": "2014-02-24T14:34:48+0000",
      "id": "707688259256219_729883773703334"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין במחירים נוחים 0507779987",
      "updated_time": "2014-02-24T12:44:28+0000",
      "id": "707688259256219_729816207043424"
    },
    {
      "message": "subleting my beautiful apt, just outside of the noisy Tel Aviv (15 min by bike),\nin Yad eliahu, quite street, close to the market and 10 min from the central station, lots of parking,\none bedroom, with kitchen, a great shower, and a huge garden that i share with great neighbors.\nlooking for a quite and clean tenant.\nfrom febuary 26 till April 10. 1900 shekel month, include bills. Yad Eliahu, Lochami galipoli st.",
      "updated_time": "2014-02-24T00:44:33+0000",
      "id": "707688259256219_729591187065926"
    },
    {
      "message": "בפחות מחודש ימים הגענו ל250 חברים. מקווה שקבוצה זו תגדל ותמשיך לעזור למחפשי הדירות לתקופה קצרה:)",
      "updated_time": "2014-02-23T19:34:26+0000",
      "id": "707688259256219_729345623757149"
    },
    {
      "message": "שבת שלום לכולם.\nמסבלט חדר בדירתי בפלורנטין, הדירה גדולה ומרווחת, מאוד מוארת ברחוב אוריאל אקוסטה אחד הרחובות המדהימים בשכונה.\nהמחיר לחדר הוא 2700 לא כולל חשבונות.\nמעדיף מעל גיל שלושים שותפה או שותף. חשבו שתהיו נקיים ומסודרים. הדירה מרוהטת קומפלט.\nאני עובד מהבית עוסק בטיפול פרטני, כך שחשוב לי שמי שייכנס לדירה יהיה אדם נעים. אני מטפל גם בחיפה כך שבכל שבוע יש לכם דירה משלכם מוצ\"ש עד שלישי . וכל שבת שניה או שלישית נוסע מיום חמישי עד שלישי.\nלפרטים נוספים אשמח לשוחח  - ניתן לשלוח הודעות בפרטי.\nהסבלט לחודש מרץ וניתן גם לאפריל הכל תלוי בכימיה :-)",
      "updated_time": "2014-02-23T13:38:32+0000",
      "id": "707688259256219_728324820525896"
    },
    {
      "message": "April in Tel-Aviv!\nIf you're looking for a beautiful apartment in the center of Tel-Aviv, check this one out!\nClick the photo for details \n",
      "updated_time": "2014-02-23T11:32:16+0000",
      "id": "707688259256219_729269077098137"
    },
    {
      "message": "Passover in Tel Aviv! come and spend the vacation in the center of TLV\n3/27-4/28\nAmazing new Apartment for Sublet near Dizengof center in Tel Aviv\nA large, spacious and beautiful 2 room apartment with balcony, in a new Building with everything you need inside, in the living room the sofa opening into a king size bed!\nall the details in the link bellow!\n\nמסבלטים את הדירה המהממת שלנו בפסח מה27/3-28/4, דירה חדשה במרכז תל אביב \nמול דיזינגוף סנטר, דקה מכל מקום...\nכל הפרטים בלינק המצורף\nחברים שתפו ותעבירו הלאה! please share!",
      "updated_time": "2014-02-23T11:12:58+0000",
      "id": "707688259256219_729263217098723"
    },
    {
      "message": "מסבלטת את הדירה לחופשת פסח. 4.4- 25.4.\nתאריכים גמישים. דירה משגעת.",
      "updated_time": "2014-02-23T08:42:36+0000",
      "id": "707688259256219_729194437105601"
    },
    {
      "message": "סאבלט לופט ענקי לחופשת פסח. 4.4-25.4\n\n",
      "updated_time": "2014-02-23T07:05:06+0000",
      "id": "707688259256219_729190050439373"
    },
    {
      "message": "חדר ביד אליהו: מסבלט חדר בתוך דירה לחודש מרץ לשותף שני לא מעשן 050-8266042",
      "updated_time": "2014-02-23T06:45:51+0000",
      "id": "707688259256219_729186693773042"
    },
    {
      "message": "סבלט בשפירא במרץ\nדירת סטודיו ליחיד או זוג או חברים ממש ממש ממש טובים.\nעם מרפסת חמודה שפונה לשמש.\nשקטה, מוארת ונעימה.\nבתאריכים 7.3-21.3\n1,600 ש\"ח.\nלפרטים נוספים:\nmayula.weinberg@gmail.com\n\nמוזמנים להעביר הלאה.\n\nתודה\n\nDear Friends,\n\nI am subletting my sweet apartment in Shapira for 2 weeks in March.\n\nSublet in Shapira in March\nOne bedroom studio apartment, for single, couple, or very very very close friends,\nSunny balcony. Good vibes.  7.3-21.3\n1,600 NIS\nFor more details: mayula.weinberg@gmail.com\n\nFeel free to share with friends.\n\nMay the force be with you.",
      "updated_time": "2014-02-21T18:42:18+0000",
      "id": "707688259256219_728092783882433"
    },
    {
      "message": "Passover in Tel Aviv! come and spend the vacation in the center of TLV\n3/27-4/28\nAmazing new Apartment for Sublet near Dizengof center in Tel Aviv\nA large, spacious and beautiful 2 room apartment with balcony, in a new Building with everything you need inside, in the living room the sofa opening into a king size bed!\nall the details in the link bellow!\n\nמסבלטים את הדירה המהממת שלנו בפסח מה27/3-28/4, דירה חדשה במרכז תל אביב \nמול דיזינגוף סנטר, דקה מכל מקום...\nכל הפרטים בלינק המצורף\nחברים שתפו ותעבירו הלאה! please share!",
      "updated_time": "2014-02-21T16:31:58+0000",
      "id": "707688259256219_728325983859113"
    },
    {
      "message": "סאבלט לופט ענקי לחופשת פסח. 4.4-25.4\n\n",
      "updated_time": "2014-02-20T21:43:08+0000",
      "id": "707688259256219_727935510564827"
    },
    {
      "message": "מסבלטת את הדירה לחופשת פסח. 4.4- 25.4.\nתאריכים גמישים. דירה משגעת.\n\ndear friends,\nI am subletting my apartment for the entire Passover holiday (April 7-24, dates are flexible). If you hear of anyone who might be interested please forward him my details",
      "updated_time": "2014-02-20T08:26:53+0000",
      "id": "707688259256219_727650027260042"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין במחירים נוחים 0507779987",
      "updated_time": "2014-02-19T16:05:46+0000",
      "id": "707688259256219_727316250626753"
    },
    {
      "message": "מסבלטת את דירת הגג שלי:\n2 חדרים כ 48 מ״ר\nגג ענק כ 85 מ״ר\nמאובזרת, שקטה וחמימה...המיקום הכי טוב בת״א (שלמה המלך- בן גוריון)\n4850 לא כולל חשבונות!",
      "updated_time": "2014-02-19T12:28:05+0000",
      "id": "707688259256219_727234267301618"
    },
    {
      "message": "דירה מדהימה בכוכב הצפון נוף לים 75 מ\"ר, 3 חדרים משופצת כניסה מידית פנויה עד 10/5/14 יש אופציה לשותפים",
      "updated_time": "2014-02-19T07:25:52+0000",
      "id": "707688259256219_727156530642725"
    },
    {
      "message": "מחפשת מישהו שיסבלט את החדר שלי בדירה ביהודה המכבי - כיכר מילאנו בין התאריכים 1.3 עד 31.5 (3 חודשים סך הכל). הדירה גדולה ומשופצת. החדר עצמו גדול מאוד ויש בו מיטה, פינת עבודה, ארון קיר, טלויזיה וסלון.\nהמטבח גדול ומאובזר, השרותים מחוץ למקלחת וגולת הכותרת - נשארת שותפה דיילת!!! המחיר 2450. עדי 052-6580852 ---עוד תמונות בפרטי---",
      "updated_time": "2014-02-18T21:34:58+0000",
      "id": "707688259256219_726958237329221"
    },
    {
      "message": "מסבלטים את הדירה המהממת שלנו, בפסח בין התאריכים 27/3-28/4!\nכל הפרטים נמצאים בלינק המצורף!!\nממליצים בחום!\nמחיר גמיש\nואם אתם לא מחפשים אז תהיו חברים ותשתפו...\n\nSublet in Tel Aviv during passover from 27/3-28/4\nall the details is in the following link \n!really recommended",
      "updated_time": "2014-02-18T07:44:04+0000",
      "id": "707688259256219_725409127484132"
    },
    {
      "message": "April Sublet in Tel-Aviv!\nDue to a trip to Vietnam, subletting our beautiful apartment in the center of Tel-Aviv\nClick the photo for details \n",
      "updated_time": "2014-02-17T11:12:43+0000",
      "id": "707688259256219_725738220784556"
    },
    {
      "message": "חברי קבוצה יקרים - מחיר הסבלוט צריך להיות נגיש ומובן לכולם לכן ,אני מזכירה שוב,הודעות ללא מחיר בגוף ההודעה תמחקנה.\nתודה ובהצלחה לכולם",
      "updated_time": "2014-02-17T11:06:09+0000",
      "id": "707688259256219_726243067400738"
    },
    {
      "message": "סאבלט, 3 חודשים - מרץ-אפריל-מאי לחדר גדול מאוד בדירה משופצת ברחוב יהודה המכבי - כיכר מילאנו (קרוב לאבן גבירול), תל אביב. ניתן לקבל את החדר מרוהט (רהיטים חדשים!). המטבח גדול ומאובזר, השירותים בחדר נפרד מהמקלחת ובדירה נשארת שותפה דיילת!!! בחדר יש מספיק מקום למיטה, שולחן עבודה, ארון קיר גדול וסלון..... בגדול, רק להיכנס. מחיר - 2450. כניסה מתחילת מרץ (ללחוצים - אפשר גם קודם). עדי 0526580852",
      "updated_time": "2014-02-16T17:25:08+0000",
      "id": "707688259256219_725911600767218"
    },
    {
      "message": "Hello, I'm looking to sublet a room starting immediately through the end of May. I can budget up to 2000 shekels. I'd prefer to live with an English speaker in order to improve my English but I will consider all opportunities. Please message me if this fits your needs as well. Thanks!",
      "updated_time": "2014-02-15T17:46:55+0000",
      "id": "707688259256219_725421244149587"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין במחירים נוחים 0507779987",
      "updated_time": "2014-02-14T17:14:36+0000",
      "id": "707688259256219_724836544208057"
    },
    {
      "message": "סבלט לשבועיים במרץ בדירת סטודיו בשכונת שפירא\n7-21.3\nמואר, נעים ושקט.\nמתאים ליחיד או זוג.\nלפרטים נוספים:mayula.weinberg@gmail.com",
      "updated_time": "2014-02-14T17:06:27+0000",
      "id": "707688259256219_724832440875134"
    },
    {
      "message": "חברים פתחתי קבוצה נוספת אתם מוזמנים להצטרף אליה\n\nhttps://www.facebook.com/groups/597157053686901/",
      "updated_time": "2014-02-13T11:59:07+0000",
      "id": "707688259256219_724161604275551"
    },
    {
      "message": "שלום, אנחנו זוג שם שני ילדים (בת שלוש ותינוק בן חודש) המחפשים דירה לתקופה של שבועיים, 13/3 עד 1/4 באזור הדר יוסף/נאות אפקה/שיכון דן או לחלופין באזור בורוכוב בגבעתיים. \nאנו מחפשים דירה מרוהטת ומצויידת לגמרי (כולל מצעים ומגבות), עדיף בגודל 3 חדרים לפחות. בחדר הילדים מספיק שתהיה מיטה אחת, עבור התינוק נשכור עריסה; נזדקק למטבח מצוייד באופן מלא, עם מקרר קטן/רגיל (אבל יותר ממקרר בר); אפשרות לעשות כביסה; אינטרנט אלחוטי וחנייה. כבלים ואפשרות גם לארח אנשים בדירה- יתרון.\nמי שיכול לעזור מוזמן לשלוח הודעה.",
      "updated_time": "2014-02-12T20:36:55+0000",
      "id": "707688259256219_723890257636019"
    },
    {
      "message": "סאבלט, 3 חודשים - מרץ-אפריל-מאי לחדר גדול מאוד בדירה מקסימה ומשופצת ברחוב יהודה המכבי - בכיכר מילאנו (קרוב לאבן גבירול), תל אביב. ניתן לקבל את החדר מרוהט (רהיטים חדשים!). המטבח גדול ומאובזר, השירותים בחדר נפרד מהמקלחת ובדירה נשארת שותפה דיילת!!! בחדר יש מספיק מקום למיטה, שולחן עבודה, ארון קיר גדול וסלון..... בגדול, רק להיכנס. מחיר - 2450. כניסה מתחילת מרץ (ללחוצים - אפשר גם קודם). עדי 0526580852",
      "updated_time": "2014-02-12T15:06:07+0000",
      "id": "707688259256219_723729444318767"
    },
    {
      "updated_time": "2014-02-11T12:22:22+0000",
      "id": "707688259256219_723147124376999"
    },
    {
      "message": "סבלט בפלורנטין בסוף פברואר לשבועיים- מה 20.2-8.3 דירת חדר גדולה עם מטבח גדול נפרד מהסלון וחדר השינה ומקלחת גדולה+ גג פרטי גדול!!\nבדירה יש הכל אפילו חתולה. פרטים בהודעה פרטית \nהמחיר כולל ארנונה וחשבונות.\nhttps://www.facebook.com/photo.php?fbid=10153803817875114&set=a.10150258927170114.497526.641070113&type=1&theater",
      "updated_time": "2014-02-10T21:17:12+0000",
      "id": "707688259256219_722874077737637"
    },
    {
      "message": "מסבלטת את החדר שלי. \nהדירה נמצאת ברחוב בן עמי ליד כיכר דיזנגוף. חדר גדול מאוד ועם מרפסת פנימית. בדירה יש שותפה נחמדה. החדר יהיה פנוי בין ה14.2 עד ה1.4 והשכירות לכל התקופה היא 2500 ש\"ח לא כולל חשבונות. \nאם מישהו מכם מעוניין או אתם מכירים מישהו שמעוניין אשמח מאוד אם תעזרו לי למצוא מישהו שיחליף אותי. אפשר ליצור איתי קשר ב 0544839207",
      "updated_time": "2014-02-10T20:52:26+0000",
      "id": "707688259256219_722863104405401"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין 0507779987",
      "updated_time": "2014-02-10T14:42:09+0000",
      "id": "707688259256219_722698551088523"
    },
    {
      "message": "חייבת לסבלט את דירת הגג הנדירה שלי בדחיפות! 2 חדרים מרווחים, נעימים, מאובזרים לגמרי! גג של כ 85 מטר...המיקום הטוב בעיר (בן גוריון-שלמה המלך)..דירה כיפית ונדירה, מתאימה ליחיד או לזוג...תקופת השכירות- לפחות חודש",
      "updated_time": "2014-02-10T08:45:27+0000",
      "id": "707688259256219_722545074437204"
    },
    {
      "message": "Sublet in April in Tel-Aviv!\nIf anyone's looking for a great flat to stay in Tel-Aviv, check this one out!\n\nClick the photo for details \n\n",
      "updated_time": "2014-02-09T13:03:45+0000",
      "id": "707688259256219_722043427820702"
    },
    {
      "message": "סבלט ל2-3 שבועות בשדרות וושינגטון, שכונת פלורנטין. חדר ענק מחולק ל2 עם מרפסת לשדרה. בדירה נשאר שותף נוח עד סוף החודש.\nאיזור מלא חנייה ותחבורה ציבורית. 10 דק הליכה לרוטשילד!\nבחדר נשאר מזרון וארון גדול.\nאפשרות לשימוש כמקום אחסון לתקופה.\nמחיר גמיש.\nלכניסה החל מה28.2 עד ה23.3.\n0542891477.",
      "updated_time": "2014-02-09T13:01:51+0000",
      "id": "707688259256219_722041731154205"
    },
    {
      "message": "סבלט בפלורנטין בסוף פברואר לשבועיים- מה 20.2-8.3 דירת חדר גדולה עם מטבח גדול נפרד מהסלון וחדר השינה  ומקלחת גדולה+ גג פרטי גדול!!\nבדירה יש הכל אפילו חתולה. פרטים בהודעה פרטית :)\nהמחיר כולל ארנונה וחשבונות.\nhttps://www.facebook.com/photo.php?fbid=10153803817875114&set=a.10150258927170114.497526.641070113&type=1&theater",
      "updated_time": "2014-02-09T11:13:16+0000",
      "id": "707688259256219_721988597826185"
    },
    {
      "message": "דירה מדהימה נוף לים, משופצת 3 חדרים, 75 מ\"ר בכוכב הצפון\nפנויה בתאריכים 15/2/14-10/5/14\nמחיר לחודש 6,000 כולל הוצאות מתאימה גם לשותפים",
      "updated_time": "2014-02-09T07:48:18+0000",
      "id": "707688259256219_721925511165827"
    },
    {
      "message": "היי! למי שמחפש סאבלט במיידי ---\nמסבלטת את חדרי לחודש החל מיום שלישי שבוע הבא (11/3 -11/2) ,\nבדירתי הממוקמת ברחוב שקט מטר מהבימה, ומשדרות רוטשילד.\nכל המעוניין לפנות בפרטי",
      "updated_time": "2014-02-08T23:40:02+0000",
      "id": "707688259256219_721781771180201"
    },
    {
      "message": "סבלט בשכונת שפירא, דרום תל אביב לשבועיים במרץ 7.3-21.3\nדירת סטודיו מוארת עם מרפסת. כיפית, שקטה ונעימה.\nמתאימה ליחיד, זוג או חברים מאוד מאוד מאוד טובים\nלפרטים נוספים: mayula.weinberg@gmail.com\n\nSublet in Shapira Neighborhood, South Tel Aviv, in March for 2 weeks\n7.3-21.3\nStudio Apartment with a sunny balcony.\nSuits a single, couple or very very very good friends\n\nFor more details: mayula.weinberg@gmail.com",
      "updated_time": "2014-02-08T19:12:29+0000",
      "id": "707688259256219_720956941262684"
    },
    {
      "message": "מחפשת סבלט בצפון תל-אביב מאמצע יוני עד אמצע יולי. מישהו?",
      "updated_time": "2014-02-07T18:04:45+0000",
      "id": "707688259256219_721099517915093"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין במחירים נוחים 0507779987",
      "updated_time": "2014-02-07T16:19:26+0000",
      "id": "707688259256219_721057804585931"
    },
    {
      "message": "מסבלט את החדר השווה שלי בדירת שני חדרים בגורדון פינת דיזינגוף (נשארת שותפה שכמעט לא בדירה) מתאריך ה9.2 עד לסוף החודש. נשאר החדר הכל (שולחן כתיבה , ארון, מיטה , שידה) למעט טלוויזיה. אפשר לבוא עם טלוויזיה ויש חיבור לHOT. הדירה משופצת כחדשה עם גינה וכל זה במחיר סמלי של 100 ש״ח ללילה כולל חשבונות. פרטים נוספים בפרטי.",
      "updated_time": "2014-02-06T16:02:25+0000",
      "id": "707688259256219_720479707977074"
    },
    {
      "message": "דירה שלושה חדרים גדולים חצי מרוהטים עם חצר גדולה במושב ליד נתניה 5 דקות \n  מכפר רופין באזור שקט ופסטורלי ב 2500 ש״ח \nכל הקודם זוכה \n0544921312",
      "updated_time": "2014-02-06T13:23:36+0000",
      "id": "707688259256219_720385024653209"
    },
    {
      "message": "אהלן חברים...\nמחפש מישהו/י לסאבלט בתאריכים:\n15/2-10/3/14\nרוטשילד באזור הבימה.. שותפה אליפות..!! Sivan Birnbaum\nדירה שלושה חדרים שני חדרי שינה וסלון, קומת קרקע עם סורגים, חדר עם מרפסת ומזגן..\nלפרטים בפרטי!",
      "updated_time": "2014-02-06T13:17:37+0000",
      "id": "707688259256219_720385727986472"
    },
    {
      "message": "חברים יקרים ,אנא רשמו את מחיר השכירות בגוף ההודעה. תודה",
      "updated_time": "2014-02-06T10:21:12+0000",
      "id": "707688259256219_720326444659067"
    },
    {
      "message": "מסבלט את הדירה המאמממממת שלי\nפלורנטין/רח צ'לנוב. מרחק הליכה מרוטשילד ומתחנה מרכזית חדשה.\n2 חדרים. 55 מטר.מאוד מוארת . עם מרפסת פרחונית ושמשית ביותר \nאינטרנט אלחוטי . מרוהטת קומפלט.. (כולל מכונת הכביסה הנאמנה שלי)\nמושלמת לזוג או ליחיד.\n\nלתקופות קצרות (עד חודש)\nלפרטים נוספים נא לפנות לפרטי.\n\ni sublet my apartment in Florentin, Chlenov street\nsunny balcony, 2 rooms, full of light and breeze. 3rd floor with an elevator, washing machine, fully furnished , wireless internet.\nin a new building.\n\nshort periods (up to a month)\nfor more details please contact through inbox",
      "updated_time": "2014-02-06T10:03:32+0000",
      "id": "707688259256219_720322034659508"
    },
    {
      "message": "דירה מדהימה נוף לים משופצת 3 חדרים 75 מ\"ר בכוכב הצפון, מרקח הליכה מפארק הירקון ומהים.",
      "updated_time": "2014-02-06T10:02:26+0000",
      "id": "707688259256219_720321781326200"
    },
    {
      "message": "-- מציאה מטורפת, סבלט בתל אביב --\nאנחנו מסבלטים את דירתנו המרווחת, השקטה והמשופצת כחדשה לתקופה של חודשיים עקב נסיעה, מתחילת מרץ עד תחילת מאי.\n65 מ\"ר, מושלמת לזוג או יחיד, מוארת מאוד, עורפית ופונה לים של ירוק - ועם זאת במיקום הכי מרכזי שיש (גן העיר, כיכר רבין ואבן גבירול במרחק דקה הליכה, 15 דקות מהסנטר). מצוידת במכשירי חשמל חדשים (כולל מכונת כביסה, מייבש, תנור ומזגנים) וברהיטי עץ קלאסיים. יש אינטרנט אלחוטי ובעצם הכל - רק להביא בגדים ומברשת שיניים ואתם גרים בדירה מהממת במרכז תל אביב.\nפרטים בפרטי.",
      "updated_time": "2014-02-04T19:29:37+0000",
      "id": "707688259256219_719417624749949"
    },
    {
      "message": "שלום לכולם,\nמפנה דירה ששכרתי (באמצע חוזה מסיבות טובות).\nדירת 2 חדרים משופצת. ברחוב יהואש, מטר מחוף גורדון. מאוד שקט \"על הים\" וקרוב למרכזי הבילוי של תל אביב.\nהדירה מרוהטת. חדר שינה מלא (מיטה זוגית קינג סייז, ארון, שידות). סלון חלקי.\nיש מזגן מרכזי ודוד שמש. בניין מטופח.\nהדירה מתאימה ליחיד או זוג (לא מתאימה לשותפים).\nלשכירות בין 4 חודשים  עם עדיפות לשנה שלמה.\nמחיר 5,500 ₪ כולל ארנונה וועד בית (כלומר נטו כ- 5,350 ₪) - אני מוכן \"לסבסד\" במעט את המחיר על מנת שיהיה אטרקטיבי. \nאשמח אם תשאירו הודעה אם רלוונטי",
      "updated_time": "2014-02-03T13:16:25+0000",
      "id": "707688259256219_718748154816896"
    },
    {
      "message": "חברי קבוצה יקרים - אנא פרסמו את מחיר שכר הדירה במודעה הגלויה לכל . פרטים אישים כמו טלפון וכ\"ו בהחלט ניתן לתת בפרטי. בהצלחה לכולם :)",
      "updated_time": "2014-02-03T11:28:54+0000",
      "id": "707688259256219_718708051487573"
    },
    {
      "message": "I'm subletting my awesome flat from 9-16.2 (flexible). It a great place at the centre of Jaffa 5 minutes walk from the flea market, the beach, great Hummus places, 10 minutes from Newe Tzedek and 15 by bike to TLV centre. PM me for further details",
      "updated_time": "2014-02-02T13:59:51+0000",
      "id": "707688259256219_718229798202065"
    },
    {
      "message": "I am looking for a roommate for a short or long  term .\n The apartment located  in wiesel street – central and very quiet and pleasant between Arlozorov to Ben Gurion.\n \nThe apartment is higly comfortable: There's a bath tub, a washing machine, a drying machine, refrigerator, oven, microwave, air conditioning.\n The rooms are very big and there is a privacy for each roommate . I am an Israeli. I'll be glad to have a roommate which is not Israeli.\n I am a very reliable and honest person. I can also assist in easing the integration in Israel.\n The rent is 2750nis for each roommate for a month plus expenses . or 100nis a day. \nfeel free to call for more details :) Hila",
      "updated_time": "2014-02-01T10:19:42+0000",
      "id": "707688259256219_717603241598054"
    },
    {
      "message": "https://www.airbnb.com/rooms/2175752\nSublet in Shapira for 2 weeks in March 7.3-21.3\nOne bedroom studio apartment, for single, couple, or very very very close friends,\nSunny balcony. Good vibes.  \nFor more details: mayula.weinberg@gmail.com",
      "updated_time": "2014-02-01T07:33:57+0000",
      "id": "707688259256219_717062498318795"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין 0507779987",
      "updated_time": "2014-01-31T15:44:45+0000",
      "id": "707688259256219_717232984968413"
    },
    {
      "message": "https://www.airbnb.com/rooms/2175752\nסבלט ליחיד/זוג/חברים ממש ממש טובים בשכונת שפירא 7-21 למרץ\n1,500 לכל התקופה כולל הכל. \nלפרטים נוספים: mayula.weinberg@gmail.com",
      "updated_time": "2014-01-31T07:21:51+0000",
      "id": "707688259256219_717061974985514"
    },
    {
      "message": "דרושה שותפה  לקבוע או לזמני.לזמני אפשר גם שותף. דירה מקסימה בצפון הישן. רחוב שקט לגמרי, שני חדרים גדולים ממוזגים , כל המכשירים החשמליים, הדירה במצב מצוין, השותפה גם .... רק להביא בגדים ולגור. שכירות 2750 ש\"ח כל אחת . יתרון למי שתפנה עכשיו נתחיל את המגורים ביחד.",
      "updated_time": "2014-01-30T14:11:38+0000",
      "id": "707688259256219_716675828357462"
    },
    {
      "message": "מסבלט חדר גדול בדירה עם שותפה בבן יהודה גורדון למשך חודש. 28/2 - 28/3.\n2500 ש\"ח כולל חשבונות\nיואל - 0523650055",
      "updated_time": "2014-01-28T23:19:42+0000",
      "id": "707688259256219_714342638590781"
    },
    {
      "message": "-- סבלט בתל אביב --\nאנחנו מסבלטים את דירתנו המרווחת, השקטה והמשופצת לחודשיים עקב נסיעה, מתחילת מרץ עד תחילת מאי.\n65 מ\"ר, מושלמת לזוג או יחיד, עורפית ופונה לים של ירוק - ועם זאת במיקום הכי מרכזי שיש (גן העיר, כיכר רבין ואבן גבירול במרחק דקה הליכה, 15 דקות מהסנטר).\nתמונות בהמשך, פרטים בפרטי.",
      "updated_time": "2014-01-28T20:37:50+0000",
      "id": "707688259256219_715580798466965"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין 0507779987",
      "updated_time": "2014-01-27T15:26:38+0000",
      "id": "707688259256219_715188348506210"
    },
    {
      "message": "שלום לכולם.. \nאני מסבלטת את חדרי החתיך בדירה הכי שווה בתל אביב! דיזנגוף 24 בייבי ;)\nמשאירה לכם 13 מ\"ר עם מזגן, טלוויזיה, גיטרה, יציאה למרפסת(40 מ\"ר!), נרגילה וגולת הכותרת-מיטה שלא תרצו לקום ממנה.. מובטח!\nאני טסה בסוף השבוע לדרום אפריקה לכל חודש פברואר ומחפשת מישהו שיהנה מהדברים  :) מיקום מעולה, בין הבימה לסנטר!\nמחיר עלות (יוצא בסביבות 2800 לחודש כולל חשבונות), פרטים בפרטי..",
      "updated_time": "2014-01-27T06:00:28+0000",
      "id": "707688259256219_714549591903419"
    },
    {
      "story": "Einat Vulkan changed the name of the group \"‎סבלט בתל אביב לתקופות קצרות‎\" to \"‎סבלט בתל אביב לתקופות קצרות‎\".",
      "updated_time": "2014-01-17T08:07:55+0000",
      "id": "707688259256219_709624392395939"
    },
    {
      "message": "שלום חברים,לוח זה מיועד לכל מי שמחפש לסבלט את דירתו לתקופה קצרה בתל אביב:) אשמח אם תעשו שיתוף יחד נביא הרבה חברים לקבוצה:)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
      "story": "Einat Vulkan updated the description of the group ‎סבלט בתל אביב לתקופות קצרות‎.",
      "updated_time": "2014-01-17T08:07:22+0000",
      "id": "707688259256219_709624295729282"
    },
    {
      "story": "Einat Vulkan changed the name of the group \"‎דירות סבלט בתל אביב בלבד לתקופה של 1-5 חודשים‎\" to \"‎סבלט בתל אביב לתקופות קצרות‎\".",
      "updated_time": "2014-01-17T08:07:21+0000",
      "id": "707688259256219_709624282395950"
    },
    {
      "message": "מחפשת להכנס לדירה בתל אביב ב1/3 עד 1/7 אם משהו שומע אשמח ...תקציב עד 3000ש\"ח",
      "updated_time": "2014-01-15T22:24:03+0000",
      "id": "707688259256219_708927679132277"
    },
    {
      "message": "ניר הובלות לסטודנטים ולחברי הקבוצה שרות אמין 0507779987",
      "updated_time": "2014-01-15T09:44:27+0000",
      "id": "707688259256219_708334169191628"
    },
    {
      "message": "here is my lovely place",
      "updated_time": "2014-01-15T09:44:21+0000",
      "id": "707688259256219_708201705871541"
    },
    {
      "story": "Einat Vulkan created a doc in the group: ‎סבלט בתל אביב לתקופות קצרות‎.",
      "updated_time": "2014-01-13T15:12:41+0000",
      "id": "707688259256219_707766732581705"
    },
    {
      "story": "Einat Vulkan changed the name of the group \"‎דירות סבלט בתל אביב בלבד לתקופה של 1-5 חודשים‎\" to \"‎דירות סבלט בתל אביב בלבד לתקופה של 1-5 חודשים‎\".",
      "updated_time": "2014-01-13T15:06:48+0000",
      "id": "707688259256219_707764502581928"
    },
    {
      "story": "Einat Vulkan created the group ‎סבלט בתל אביב לתקופות קצרות‎.",
      "updated_time": "2014-01-13T11:30:54+0000",
      "id": "707688259256219_707688265922885"
    }
  ],
  "paging": {
    "previous": "https://graph.facebook.com/v2.4/707688259256219/feed?limit=1000&format=json&__paging_token=enc_AdDfZCWJzbHcgvCnpv4soCXfGbXgSPNxCT6RZAegD6ZAWTKzSvBCsIu7IKp5F0qClxka9IAcNBk1YBnovsWKN80tO4YFZARa5FrBg5qXBqDtvrpgPwZDZD&since=1393256915&access_token=CAACEdEose0cBAHFTnXdZAvd7RtEomhXVVYGrkIJuHms70bEovtxrO0bBk2PWP0PHhERoiKVG2S7ZCYayGIt6ULeJZCFMhHT4m1xTqCC5XDd1d2z2alIUxw6A5ZBf8Ss0FEx6llS3TAtyVpk4f91043aohdeXNRqxf9o8t5y75ZBHkEDXYYdSXH77Lp9JskakRXZAnhatUX0AZDZD&__previous=1",
    "next": "https://graph.facebook.com/v2.4/707688259256219/feed?limit=1000&format=json&__paging_token=enc_AdDyjdPljZA8UUhqeer4uOYz9zZBS0ltgyzutg9DJitTuezgtPbLWDuSeb0y3H73zsBHU6ne6BcPOCArCcVmhYDDwtXBi6QELNemZAzVxWbWYb3fgZDZD&access_token=CAACEdEose0cBAHFTnXdZAvd7RtEomhXVVYGrkIJuHms70bEovtxrO0bBk2PWP0PHhERoiKVG2S7ZCYayGIt6ULeJZCFMhHT4m1xTqCC5XDd1d2z2alIUxw6A5ZBf8Ss0FEx6llS3TAtyVpk4f91043aohdeXNRqxf9o8t5y75ZBHkEDXYYdSXH77Lp9JskakRXZAnhatUX0AZDZD&until=1389612654"
  }
}